"""empty message

Revision ID: 393ad64874d1
Revises: 2b6ca9ab0c6e
Create Date: 2023-05-07 09:40:27.990876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '393ad64874d1'
down_revision = '2b6ca9ab0c6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel_memberships', schema=None) as batch_op:
        batch_op.drop_column('type')

    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.drop_constraint('fk_channels_team_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_channels_team_id_teams'), 'teams', ['team_id'], ['id'])

    with op.batch_alter_table('team_memberships', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=7),
               existing_nullable=True)

    with op.batch_alter_table('team_memberships', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=9),
               existing_nullable=True)

    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_channels_team_id_teams'), type_='foreignkey')
        batch_op.create_foreign_key('fk_channels_team_id_users', 'users', ['team_id'], ['id'])

    with op.batch_alter_table('channel_memberships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=14), nullable=True))

    # ### end Alembic commands ###
