"""empty message

Revision ID: 89dade9d4629
Revises: d8e39c17f592
Create Date: 2023-05-11 18:48:42.830050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89dade9d4629'
down_revision = 'd8e39c17f592'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_messages_channel_id_channels', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_messages_channel_id_channels'), 'channels', ['channel_id'], ['id'], ondelete='cascade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_messages_channel_id_channels'), type_='foreignkey')
        batch_op.create_foreign_key('fk_messages_channel_id_channels', 'channels', ['channel_id'], ['id'])

    # ### end Alembic commands ###
