"""empty message

Revision ID: d8e39c17f592
Revises: 680ad0db8df7
Create Date: 2023-05-11 18:41:31.346079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8e39c17f592'
down_revision = '680ad0db8df7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.drop_constraint('fk_channels_team_id_teams', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_channels_team_id_teams'), 'teams', ['team_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_channels_team_id_teams'), type_='foreignkey')
        batch_op.create_foreign_key('fk_channels_team_id_teams', 'teams', ['team_id'], ['id'])

    # ### end Alembic commands ###
