"""empty message

Revision ID: 1e2bb935a003
Revises: 397fb29a607e
Create Date: 2023-05-10 15:44:11.431131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e2bb935a003'
down_revision = '397fb29a607e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_messages_channel_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_messages_channel_id_channels'), 'channels', ['channel_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_messages_channel_id_channels'), type_='foreignkey')
        batch_op.create_foreign_key('fk_messages_channel_id_users', 'users', ['channel_id'], ['id'])

    # ### end Alembic commands ###
