"""empty message

Revision ID: 397fb29a607e
Revises: 393ad64874d1
Create Date: 2023-05-07 17:14:37.508916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '397fb29a607e'
down_revision = '393ad64874d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=150), nullable=True))

    # ### end Alembic commands ###
